(() => {
  'use strict';
  const $=id=>document.getElementById(id),cfg=SIGMUN_CONFIG;
  const state={topics:[],projects:[],project:null,defs:[],layers:new Map(),selected:null,rows:[],filtered:[],chart:null,currentBase:'osm',drawControl:null,drawVisible:false,measureMode:false};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  let toastTimer;function toast(m,e=false){const x=$('toast');x.textContent=m;x.classList.toggle('error',e);x.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>x.classList.remove('show'),2800)}
  const map=L.map('map',{center:cfg.defaultCenter,zoom:cfg.defaultZoom,zoomControl:false,preferCanvas:true});
  const bases={osm:L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}),satellite:L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'© Esri'}),terrain:L.tileLayer('https://{s}.tile.opentopomap.org/{z}/{x}/{y}.png',{maxZoom:17,attribution:'© OpenTopoMap'})};bases.osm.addTo(map);
  const drawings=L.featureGroup().addTo(map);state.drawControl=new L.Control.Draw({edit:{featureGroup:drawings},draw:{circle:false,circlemarker:false}});
  map.on(L.Draw.Event.CREATED,e=>{drawings.addLayer(e.layer);if(state.measureMode&&e.layer instanceof L.Polyline){const pts=e.layer.getLatLngs().flat(Infinity);let meters=0;for(let i=1;i<pts.length;i++)meters+=pts[i-1].distanceTo(pts[i]);toast(`Distancia: ${meters>=1000?(meters/1000).toFixed(2)+' km':Math.round(meters)+' m'}`);state.measureMode=false}});

  async function init(){try{state.topics=await SigmunDB.topics();state.projects=await SigmunDB.projects();fillTopics();const slug=new URLSearchParams(location.search).get('project'),p=state.projects.find(x=>x.slug===slug)||state.projects.find(x=>x.project_type!=='dashboard')||state.projects[0];if(p){$('topicSelect').value=p.topic_id;fillProjects(p.topic_id,p.id);await selectProject(p.id)}}catch(e){console.error(e);toast(e.message,true)}}
  function fillTopics(){$('topicSelect').innerHTML=state.topics.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');$('topicSelect').onchange=e=>{fillProjects(e.target.value);const id=$('projectSelect').value;if(id)selectProject(id)}}
  function fillProjects(topicId,sel){const arr=state.projects.filter(p=>p.topic_id===topicId&&p.project_type!=='dashboard');$('projectSelect').innerHTML=arr.map(p=>`<option value="${p.id}" ${p.id===sel?'selected':''}>${esc(p.name)}</option>`).join('');$('projectSelect').onchange=e=>selectProject(e.target.value)}
  async function selectProject(id){state.project=state.projects.find(p=>p.id===id);if(!state.project)return;clearProjectLayers();$('headerTitle').textContent=state.project.name;$('headerSubtitle').textContent=state.project.sigmun_topics?.name||'SIGmun Delicias';$('mapTitle').textContent=state.project.name;$('mapDesc').textContent=state.project.description||'';$('dashLink').href=`dashboard.html?project=${encodeURIComponent(state.project.slug)}`;map.setView([state.project.center_lat||cfg.defaultCenter[0],state.project.center_lon||cfg.defaultCenter[1]],state.project.default_zoom||cfg.defaultZoom);state.defs=await SigmunDB.geoLayers(id);await loadDefs()}
  function clearProjectLayers(){for(const x of state.layers.values()){if(map.hasLayer(x.leaflet))map.removeLayer(x.leaflet)}state.layers.clear();state.selected=null;state.rows=[];state.filtered=[];renderLayerList();refreshData();renderMapLegend()}
  function featureId(f,i=0){return String(f?.id??f?.properties?.id??i)}
  function makeLayer(def,gj,index){
    const style=SigmunTheme.normalizeStyle(def.style||{}),pane=`sigmun-${String(def.id).replace(/-/g,'').slice(0,12)}`;if(!map.getPane(pane)){map.createPane(pane);map.getPane(pane).style.zIndex=String(650-index*3)}
    const canvas=L.canvas({pane,padding:.35,tolerance:4}),subgroups=SigmunTheme.isKmlRenderer(style)?SigmunTheme.kmlSubgroups(gj.features||[],style):[],fidToGroup=new Map();subgroups.forEach(g=>g.featureIds.forEach(id=>fidToGroup.set(String(id),g.key)));
    const leaflet=L.geoJSON(gj,{pane,renderer:canvas,style:f=>({...SigmunTheme.leafletPathStyle(style,f,1),pane,renderer:canvas}),pointToLayer:(f,ll)=>L.circleMarker(ll,{...SigmunTheme.leafletPointStyle(style,f,1),pane,renderer:canvas}),onEachFeature:(f,l)=>{l.__sigmunFeature=f;l.__sigmunGroup=fidToGroup.get(featureId(f))||'';const label=style.labelField?f.properties?.[style.labelField]:f.properties?.name;if(label!==undefined&&label!==null&&label!=='')l.bindTooltip(String(label),{sticky:true,direction:'top'});l.on('click',()=>{showProps(f,def);selectLayer(def.id)})}});
    const children=[];leaflet.eachLayer(l=>children.push(l));return{def,geojson:gj,leaflet,pane,style,canvas,opacity:1,subgroups,disabledSubgroups:new Set(),children};
  }
  async function loadDefs(){if(!state.defs.length){renderLayerList();renderMapLegend();return}const sorted=[...state.defs].sort((a,b)=>(a.sort_order||0)-(b.sort_order||0)||a.name.localeCompare(b.name,'es'));for(let i=0;i<sorted.length;i++){const d=sorted[i];try{const gj=await SigmunDB.geojson(d.id),obj=makeLayer(d,gj,i);if(d.is_visible!==false)obj.leaflet.addTo(map);state.layers.set(d.id,obj)}catch(e){console.error('Capa',d.name,e)}}renderLayerList();renderMapLegend();const first=sorted[0];if(first){selectLayer(first.id);fitAll()}}
  function rendererName(r){return r==='kml'?'Estilo KML original':r==='categorized'?'Categorías':r==='graduated'?'Rangos':'Símbolo único'}
  function visibleFeatures(x){if(!x)return[];if(!x.disabledSubgroups.size)return x.geojson.features||[];return(x.geojson.features||[]).filter((f,i)=>{const id=featureId(f,i),group=x.subgroups.find(g=>g.featureIds.has(id));return!group||!x.disabledSubgroups.has(group.key)})}
  function miniLegend(obj){const items=SigmunTheme.legendItems(obj.style,visibleFeatures(obj)).slice(0,6),all=SigmunTheme.legendItems(obj.style,visibleFeatures(obj));if(obj.style.renderer==='single'||!items.length)return'';return`<div class="layer-mini-legend">${items.map(i=>`<span title="${esc(i.label)}"><i style="background:${i.color}"></i>${esc(i.label)}</span>`).join('')}${all.length>6?`<em>+${all.length-6}</em>`:''}</div>`}
  function collectionGroups(arr){const mapg=new Map();for(const x of arr){const m=x.def.metadata||{},key=m.import_group_id?`g:${m.import_group_id}`:'standalone',title=m.source_collection||'Capas independientes';if(!mapg.has(key))mapg.set(key,{key,title,layers:[]});mapg.get(key).layers.push(x)}return[...mapg.values()]}
  function subgroupRows(x){if(!x.subgroups.length)return'';return`<details class="layer-subgroups" ${x.def.id===state.selected?'open':''}><summary>${x.subgroups.length} categorías / subcarpetas</summary><div class="subgroup-actions"><button type="button" data-sub-all="${x.def.id}">Todas</button><button type="button" data-sub-none="${x.def.id}">Ninguna</button></div><div class="subgroup-list">${x.subgroups.map(g=>`<label class="subgroup-row"><input type="checkbox" data-sub-toggle="${x.def.id}" data-sub-key="${esc(g.key)}" ${x.disabledSubgroups.has(g.key)?'':'checked'}><i style="background:${g.color}"></i><span title="${esc(g.displayLabel||g.label)}">${esc(g.displayLabel||g.label)}</span><em>${g.count.toLocaleString('es-MX')}</em></label>`).join('')}</div></details>`}
  function layerCard(x){const active=map.hasLayer(x.leaflet),features=visibleFeatures(x),c=SigmunTheme.colorForFeature(x.style,features[0]||x.geojson.features?.[0]||{});return`<div class="layer-item ${x.def.id===state.selected?'selected':''}" data-layer-card="${x.def.id}"><div class="layer-row"><label class="layer-check" title="Mostrar/ocultar capa"><input type="checkbox" data-toggle="${x.def.id}" ${active?'checked':''}><span></span></label><span class="dot" style="background:${c}"></span><button class="layer-name" data-select="${x.def.id}">${esc(x.def.name)}</button><div class="layer-tools"><button class="mini-icon" data-zoom="${x.def.id}" title="Acercar"><i class="bi bi-search"></i></button></div></div><div class="layer-meta">${esc(rendererName(x.style.renderer))} · ${features.length.toLocaleString('es-MX')} / ${(x.geojson.features||[]).length.toLocaleString('es-MX')} elementos</div><div class="layer-opacity-row"><span>Opacidad</span><input type="range" data-opacity="${x.def.id}" min="0" max="100" value="${Math.round(x.opacity*100)}" aria-label="Opacidad de ${esc(x.def.name)}"><b>${Math.round(x.opacity*100)}%</b></div>${subgroupRows(x)}${miniLegend(x)}</div>`}
  function renderLayerList(){
    const arr=[...state.layers.values()].sort((a,b)=>(a.def.sort_order||0)-(b.def.sort_order||0)),groups=collectionGroups(arr);$('layerList').innerHTML=arr.length?groups.map(g=>`<section class="viewer-layer-group"><div class="viewer-layer-group-head"><div><i class="bi bi-collection"></i><b>${esc(g.title)}</b><span>${g.layers.length} capa${g.layers.length===1?'':'s'}</span></div><div><button type="button" data-group-show="${esc(g.key)}">Todas</button><button type="button" data-group-hide="${esc(g.key)}">Ninguna</button></div></div>${g.layers.map(layerCard).join('')}</section>`).join(''):'<div class="empty">Este proyecto todavía no tiene capas geográficas publicadas.</div>';
    document.querySelectorAll('[data-select]').forEach(b=>b.onclick=()=>selectLayer(b.dataset.select));document.querySelectorAll('[data-zoom]').forEach(b=>b.onclick=()=>zoomLayer(b.dataset.zoom));
    document.querySelectorAll('[data-toggle]').forEach(inp=>inp.onchange=()=>setLayerVisible(inp.dataset.toggle,inp.checked));
    document.querySelectorAll('[data-opacity]').forEach(inp=>inp.oninput=()=>{const x=state.layers.get(inp.dataset.opacity);if(!x)return;x.opacity=Number(inp.value)/100;inp.nextElementSibling.textContent=`${inp.value}%`;applyLayerStyle(x);renderMapLegend()});
    document.querySelectorAll('[data-sub-toggle]').forEach(inp=>inp.onchange=()=>toggleSubgroup(inp.dataset.subToggle,inp.dataset.subKey,inp.checked));
    document.querySelectorAll('[data-sub-all]').forEach(b=>b.onclick=()=>setAllSubgroups(b.dataset.subAll,true));document.querySelectorAll('[data-sub-none]').forEach(b=>b.onclick=()=>setAllSubgroups(b.dataset.subNone,false));
    document.querySelectorAll('[data-group-show]').forEach(b=>b.onclick=()=>setCollectionVisible(b.dataset.groupShow,true));document.querySelectorAll('[data-group-hide]').forEach(b=>b.onclick=()=>setCollectionVisible(b.dataset.groupHide,false));
    updateDataSelect();updateVisibleCount();
  }
  function setLayerVisible(id,on,rerender=true){const x=state.layers.get(id);if(!x)return;if(on){if(!map.hasLayer(x.leaflet))x.leaflet.addTo(map)}else if(map.hasLayer(x.leaflet))map.removeLayer(x.leaflet);if(rerender){renderLayerList();renderMapLegend()}}
  function setCollectionVisible(key,on){for(const x of state.layers.values()){const m=x.def.metadata||{},k=m.import_group_id?`g:${m.import_group_id}`:'standalone';if(k===key)setLayerVisible(x.def.id,on,false)}renderLayerList();renderMapLegend()}
  function setAllSubgroups(id,on){const x=state.layers.get(id);if(!x)return;x.disabledSubgroups.clear();if(!on)x.subgroups.forEach(g=>x.disabledSubgroups.add(g.key));syncSubgroups(x);afterSubgroupChange(x)}
  function toggleSubgroup(id,key,on){const x=state.layers.get(id);if(!x)return;on?x.disabledSubgroups.delete(key):x.disabledSubgroups.add(key);syncSubgroups(x);afterSubgroupChange(x)}
  function syncSubgroups(x){for(const child of x.children){const key=child.__sigmunGroup,should=!key||!x.disabledSubgroups.has(key),has=x.leaflet.hasLayer(child);if(should&&!has)x.leaflet.addLayer(child);else if(!should&&has)x.leaflet.removeLayer(child)}applyLayerStyle(x)}
  function afterSubgroupChange(x){if(state.selected===x.def.id)selectLayer(x.def.id,false);renderLayerList();renderMapLegend()}
  function applyLayerStyle(x){for(const child of x.children){const f=child.__sigmunFeature;if(!f)continue;if(child.setStyle){const opt=f.geometry?.type==='Point'?SigmunTheme.leafletPointStyle(x.style,f,x.opacity):SigmunTheme.leafletPathStyle(x.style,f,x.opacity);child.setStyle(opt);if(f.geometry?.type==='Point'&&child.setRadius&&opt.radius)child.setRadius(opt.radius)}}}
  function updateVisibleCount(){const total=state.layers.size,visible=[...state.layers.values()].filter(x=>map.hasLayer(x.leaflet)).length;if($('visibleLayerCount'))$('visibleLayerCount').textContent=`${visible} de ${total} visibles`}
  $('showAllLayers').onclick=()=>{for(const x of state.layers.values()){x.disabledSubgroups.clear();syncSubgroups(x);setLayerVisible(x.def.id,true,false)}renderLayerList();renderMapLegend();fitAll()};
  $('hideAllLayers').onclick=()=>{for(const x of state.layers.values())setLayerVisible(x.def.id,false,false);renderLayerList();renderMapLegend()};
  function renderMapLegend(){const visible=[...state.layers.values()].filter(x=>map.hasLayer(x.leaflet)&&x.style.legend?.show!==false).sort((a,b)=>(a.def.sort_order||0)-(b.def.sort_order||0));if(!visible.length){$('mapLegend').innerHTML='';$('mapLegend').classList.remove('show');updateVisibleCount();return} $('mapLegend').innerHTML=`<div class="map-legend-head"><b>Leyenda</b><span>${visible.length} capa${visible.length===1?'':'s'} visible${visible.length===1?'':'s'}</span></div>`+visible.map(x=>{const items=SigmunTheme.legendItems(x.style,visibleFeatures(x));return`<div class="map-legend-block"><strong>${esc(x.style.legend?.title||x.def.name)}</strong>${x.style.renderer==='kml'?'<small>Estilo original KML/KMZ</small>':x.style.field?`<small>${esc(x.style.field)}</small>`:''}<div>${items.slice(0,80).map(i=>`<span class="map-legend-item"><i style="background:${i.color};opacity:${x.opacity}"></i>${esc(i.label)}${i.count?` <em>${i.count.toLocaleString('es-MX')}</em>`:''}</span>`).join('')}</div></div>`}).join('');$('mapLegend').classList.add('show');updateVisibleCount()}
  function selectLayer(id,rerender=true){state.selected=id;const x=state.layers.get(id),features=visibleFeatures(x);state.rows=features.map((f,i)=>({__fid:featureId(f,i),__geometry:f.geometry?.type,...Object.fromEntries(Object.entries(f.properties||{}).filter(([k])=>!k.startsWith('_kml_')))}));state.filtered=[...state.rows];if(rerender)renderLayerList();refreshData()}
  function updateDataSelect(){$('dataLayer').innerHTML=[...state.layers.values()].sort((a,b)=>(a.def.sort_order||0)-(b.def.sort_order||0)).map(x=>`<option value="${x.def.id}" ${x.def.id===state.selected?'selected':''}>${esc(x.def.name)}</option>`).join('');$('dataLayer').onchange=e=>selectLayer(e.target.value)}
  function refreshData(){renderTable();setupFilters();renderAnalysis()}
  function applyFilters(){const term=$('searchInput').value.toLowerCase(),f=$('filterField').value,v=$('filterValue').value;state.filtered=state.rows.filter(r=>(!term||Object.values(r).some(x=>String(x??'').toLowerCase().includes(term)))&&(!f||!v||String(r[f]??'')===v));renderTable();renderAnalysis(false)}
  function setupFilters(){const fields=state.rows.length?Object.keys(state.rows[0]).filter(f=>!f.startsWith('__')):[];$('filterField').innerHTML='<option value="">Campo</option>'+fields.map(f=>`<option>${esc(f)}</option>`).join('');$('filterField').onchange=()=>{const f=$('filterField').value,vals=[...new Set(state.rows.map(r=>String(r[f]??'')).filter(Boolean))].slice(0,300);$('filterValue').innerHTML='<option value="">Todos</option>'+vals.map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');applyFilters()};$('filterValue').onchange=applyFilters;$('searchInput').oninput=applyFilters}
  function renderTable(){if(!state.filtered.length){$('dataTable').innerHTML='<tbody><tr><td style="padding:15px">Sin registros.</td></tr></tbody>';return}const fields=Object.keys(state.filtered[0]).filter(f=>f!=='__fid').slice(0,18);$('dataTable').innerHTML=`<thead><tr>${fields.map(f=>`<th>${esc(f)}</th>`).join('')}</tr></thead><tbody>${state.filtered.slice(0,750).map(r=>`<tr>${fields.map(f=>`<td title="${esc(r[f])}">${esc(r[f])}</td>`).join('')}</tr>`).join('')}</tbody>`}
  function renderAnalysis(resetField=true){if(state.chart){state.chart.destroy();state.chart=null}const s=SigmunData.summarize(state.filtered);$('analysisKpis').innerHTML=`<div class="kpi"><span>Elementos</span><b>${s.count}</b></div><div class="kpi"><span>Campos</span><b>${s.fields.length}</b></div><div class="kpi"><span>Numéricos</span><b>${s.numeric.length}</b></div><div class="kpi"><span>Filtrados</span><b>${state.rows.length-state.filtered.length}</b></div>`;const fields=s.categorical.length?s.categorical:s.fields.slice(0,8);if(resetField)$('chartField').innerHTML=fields.map(f=>`<option>${esc(f)}</option>`).join('');const f=$('chartField').value||fields[0];if(f)drawChart(f)}
  function drawChart(f){if(state.chart)state.chart.destroy();const counts=SigmunData.counts(state.filtered,f),layer=state.layers.get(state.selected),style=layer?.style||SigmunTheme.normalizeStyle({}),legend=SigmunTheme.legendItems(style,visibleFeatures(layer));const colors=counts.map((x,i)=>{if(style.renderer==='categorized'&&style.field===f)return SigmunTheme.colorForValue(style,x[0]);if(style.renderer==='kml'){const hit=legend.find(l=>String(l.label).replace(/ · estilo \d+$/,'')===String(x[0]));if(hit)return hit.color}return SigmunTheme.colorAt(i,counts.length,'categorical')});state.chart=new Chart($('chart'),{type:'bar',data:{labels:counts.map(x=>x[0]),datasets:[{data:counts.map(x=>x[1]),backgroundColor:colors,borderRadius:5}]},options:{responsive:true,maintainAspectRatio:false,indexAxis:counts.length>8?'y':'x',plugins:{legend:{display:false}},scales:{x:{ticks:{font:{size:8}}},y:{ticks:{font:{size:8}}}}}})}
  $('chartField').onchange=e=>drawChart(e.target.value);
  function showProps(f,def){const style=SigmunTheme.normalizeStyle(def?.style||{}),k=SigmunTheme.kmlResolvedStyle(style,f),isKml=SigmunTheme.isKmlRenderer(style),p=f.properties||{},origin=isKml?`<div class="prop thematic-prop"><span>Simbología original</span><b><i style="background:${k.fillColor||k.lineColor}"></i>${esc(p._kml_style||'Estilo KML')}</b></div>${p._kml_document?`<div class="prop"><span>Documento KML</span><b>${esc(p._kml_document)}</b></div>`:''}${(p._kml_folder_path||p._kml_folder)?`<div class="prop"><span>Carpeta / subcarpeta</span><b>${esc(p._kml_folder_path||p._kml_folder)}</b></div>`:''}`:(style.field?`<div class="prop thematic-prop"><span>Simbología</span><b><i style="background:${SigmunTheme.colorForFeature(style,f)}"></i>${esc(style.field)}: ${esc(p[style.field]??'Sin dato')}</b></div>`:'');const attrs=Object.entries(p).filter(([key])=>!key.startsWith('_kml_'));$('propertyBody').innerHTML=origin+(attrs.map(([key,v])=>`<div class="prop"><span>${esc(key)}</span><b>${esc(typeof v==='object'?JSON.stringify(v):v)}</b></div>`).join('')||'<div class="empty">Sin atributos.</div>');$('propertyDrawer').classList.add('open')}
  $('closeProps').onclick=()=>$('propertyDrawer').classList.remove('open');
  function zoomLayer(id){const b=state.layers.get(id)?.leaflet.getBounds();if(b?.isValid())map.fitBounds(b,{padding:[35,35],maxZoom:17})}
  function fitAll(){const list=[...state.layers.values()].filter(x=>map.hasLayer(x.leaflet));if(!list.length)return;const b=L.featureGroup(list.map(x=>x.leaflet)).getBounds();if(b?.isValid())map.fitBounds(b,{padding:[30,30],maxZoom:16})}

  document.querySelectorAll('.viewer-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.viewer-tab').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.view-pane').forEach(x=>x.classList.toggle('active',x.dataset.pane===b.dataset.tab))});
  document.querySelectorAll('.base-btn').forEach(b=>b.onclick=()=>{map.removeLayer(bases[state.currentBase]);state.currentBase=b.dataset.base;bases[state.currentBase].addTo(map);document.querySelectorAll('.base-btn').forEach(x=>x.classList.toggle('active',x===b))});
  $('panelBtn').onclick=()=>$('viewerPanel').classList.toggle('open');map.on('mousemove',e=>$('coords').textContent=`Lat: ${e.latlng.lat.toFixed(6)} | Lon: ${e.latlng.lng.toFixed(6)}`);
  $('homeBtn').onclick=()=>state.project?map.setView([state.project.center_lat||cfg.defaultCenter[0],state.project.center_lon||cfg.defaultCenter[1]],state.project.default_zoom||cfg.defaultZoom):map.setView(cfg.defaultCenter,cfg.defaultZoom);
  $('fullBtn').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();$('printBtn').onclick=()=>window.print();$('locateBtn').onclick=()=>map.locate({setView:true,maxZoom:17});map.on('locationerror',()=>toast('No fue posible obtener tu ubicación.',true));
  $('drawBtn').onclick=()=>{state.drawVisible=!state.drawVisible;if(state.drawVisible)map.addControl(state.drawControl);else map.removeControl(state.drawControl);$('drawBtn').classList.toggle('active',state.drawVisible)};$('measureBtn').onclick=()=>{state.measureMode=true;new L.Draw.Polyline(map,{shapeOptions:{color:'#0f4fa8',weight:3}}).enable();toast('Traza una línea para medir la distancia.')};
  $('exportBtn').onclick=()=>{const x=state.layers.get(state.selected);if(!x)return;const ids=new Set(state.filtered.map(r=>String(r.__fid))),gj={type:'FeatureCollection',features:visibleFeatures(x).filter((f,i)=>ids.has(featureId(f,i)))};SigmunData.download(`${(x.def.name||'capa').replace(/\s+/g,'_')}.geojson`,JSON.stringify(gj,null,2),'application/geo+json')};
  init();
})();
